version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=

  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - ./volumes/milvus/data:/var/lib/milvus/data
      - ./volumes/milvus/conf:/var/lib/milvus/conf
      - ./volumes/milvus/logs:/var/lib/milvus/logs
    restart: always
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530